sudo: required
dist: trusty
language: php
matrix:
  include:
    - php:
      - 5.4
      - 5.5
      - 5.6
      sudo: required
      dist: trusty
      before_script: 
        - curl -sSfL -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar
        - sudo add-apt-repository ppa:chris-lea/libsodium -y
        - sudo sh -c 'echo "deb http://ppa.launchpad.net/chris-lea/libsodium/ubuntu trusty main" >> /etc/apt/sources.list'
        - sudo sh -c 'echo "deb-src http://ppa.launchpad.net/chris-lea/libsodium/ubuntu trusty main" >> /etc/apt/sources.list'
        - sudo apt-get update && sudo apt-get install libsodium-dev -y
        - pecl install libsodium-1.0.7
      script:
        - phpenv config-add sodium.ini
        - vendor/bin/phpunit --testsuite unit
      install:
        - travis_retry composer install --no-interaction --prefer-source
      notifications:
        webhooks: $ZAPIER_WEBHOOK_URL
    - php: 
      - 7.0
      - 7.1
      - 7.2
      - hhvm-3.24
      sudo: required
      dist: trusty
      before_script: 
        - curl -sSfL -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar
        - sudo add-apt-repository ppa:ondrej/php -y
        - sudo apt-get update && sudo apt-get install libsodium-dev -y
        - pecl install libsodium-2.0.11
      script:
        - phpenv config-add sodium.ini
        - vendor/bin/phpunit --testsuite unit
      install:
        - travis_retry composer install --no-interaction --prefer-source
      notifications:
        webhooks: $ZAPIER_WEBHOOK_URL
    - php: 
      - 5.6 # Arbitrarily testing 5.6 (a version without libsodium support)
      dist: trusty
      before_script: 
        - curl -sSfL -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar
      script:
        - vendor/bin/phpunit --testsuite unit
      install:
        - travis_retry composer install --no-interaction --prefer-source
      notifications:
        webhooks: $ZAPIER_WEBHOOK_URL
    
    